- .travis.yml
- Guardfile
- simp-rake-helpers.gemspec
SIMP-64 #close
SIMP-40 #comment Gem for 1.0.3 release is ready for publication
SIMP-23 #comment Gem for 1.0.3 release is ready for publication
> (SIMP-64) Add missing files to manifest in .gemspec

- CHANGELOG.md
- lib/simp/rake/helpers.rb
- lib/simp/rpm.rb
This patch adds support for reading RPM information directly from RPM
files as well as RPM spec files.
It also removes some legacy style cruft
SIMP-193 #close
> (SIMP-193) Support reading RPM files

- CHANGELOG.md
- lib/simp/rake/helpers.rb
- simp-rake-helpers.gemspec
This patch cleans up some gemspec cruft after SIMP-193
SIMP-193 #close
> (SIMP-193) Supplementary cleanup

- lib/simp/rake/pkg.rb
Not ignoring everything is probably a good thing.
SIMP-226 #comment Had a logic error
> (SIMP-226) Fixed an issue with ordering

- lib/simp/rake/pkg.rb
This should be the last issue.
Directories need to be ignored *after* the usual suspects.
SIMP-226 #comment Need to ignore directories last
> (SIMP-226) Another ordering issue

- CHANGELOG.md
- README.md
- simp-rake-helpers.gemspec
SIMP-208 #comment Updated CHANGELOG for 1.0.10 release
> (SIMP-208) Update CHANGELOG for 1.0.10 release

- lib/simp/rake/build/auto.rb
- lib/simp/rake/build/iso.rb
- lib/simp/rake/build/pkg.rb
- lib/simp/rake/helpers/version.rb
SIMP-912 #comment bumped gem version to 1.1.1
SIMP-912 #close #comment Fixed path to `vermap.yaml`
> (SIMP-912) Fix path to `vermap.yaml`

- lib/simp/rake/build/auto.rb
- lib/simp/rake/helpers/version.rb
SIMP-958 #close #comment Good news for CentOS 6.7
> (SIMP-958) `build:auto` includes multiple disks

- lib/simp/rake/fixtures.rb
- lib/simp/rake/helpers.rb
- lib/simp/rake/helpers/version.rb
- lib/simp/rake/pupmod/helpers.rb
SIMP-1009 #close
Change-Id: I065097fa97419fe74f375eb76c6d64b69824c084
> (SIMP-1009) Include `fixtures:` tasks

- lib/simp/rake/build/pkg.rb
- lib/simp/rake/helpers/version.rb
Executing a socket doesn't generally do what you want it to!
SIMP-1107 #close
> (SIMP-1107) Fix issue in gpg socket usage

- CHANGELOG.md
- lib/simp/rake/helpers/version.rb
- lib/simp/rake/pkg.rb
- lib/simp/rpm.rb
This fixes a few bugs and adds support for the new LUA-based RPM spec
file changes that will eventually make their way into this Gem directly.
SIMP-991 #comment Update for the RPM spec files
> (SIMP-991) Updates for new RPM spec files

- README.md
Forgot to update the README for the new functionality.
SIMP-1811 #close #comment README Update
> (SIMP-1181) README Update

- CHANGELOG.md
- lib/simp/rake/helpers/rpm_spec.rb
- lib/simp/rake/helpers/version.rb
* Ensure that RPM names are properly structured between SIMP and non-SIMP RPMs
* Make sure that the install path is proper
SIMP-1243 #close
> (SIMP-1243) Handle SIMP and non-SIMP RPMs properly

- CHANGELOG.md
- lib/simp/rake/build/deps.rb
- lib/simp/rake/helpers/version.rb
Fixed bugs whereby generated Puppetfile.stable files were malformed.
> (SIMP-1507) Malformed generated Puppetfile.stable

- CHANGELOG.md
- lib/simp/rake.rb
- lib/simp/rake/build/build.rb
- lib/simp/rake/build/pkg.rb
- lib/simp/rake/build/tar.rb
- lib/simp/rake/fixtures.rb
- lib/simp/rake/helpers/version.rb
* Added thread safe failure checks
* Will raise an error when building the modules if one or more
fails
* Ensure that the packages.yaml file is 'human clean'
* Made the repoclosure error detection more aggressive
SIMP-1508 #comment Fixed multiple minor issues across the Gem
SIMP-1548 #close
SIMP-1549 #close
Change-Id: Ib4619566840cb492a07f5a13487cf859fdfca07a
> (SIMP-1508) Multiple minor fixes

- CHANGELOG.md
- lib/simp/rake/build/auto.rb
- lib/simp/rake/helpers/version.rb
Needed to re-enable the tasks and ensure that we were in the correct
directory at all times.
Looping through all versions should work correctly now.
SIMP-2253 #close
> (SIMP-2253) Fix loop support

- .travis.yml
- CHANGELOG.md
- lib/simp/rake/helpers/version.rb
- lib/simp/rake/pupmod/helpers.rb
Dependency on semantic_puppet changed with Puppet 4.9+
https://github.com/garethr/puppet-module-skeleton/pull/137/files
SIMP-2568 #close
> (SIMP-2568) Updated requirement on semantic_puppet

- CHANGELOG.md
- lib/simp/rake/build/pkg.rb
- lib/simp/rake/helpers/version.rb
- simp-rake-helpers.gemspec
* Handle moving the GPGKEYS properly
* Add the dev key to the ISO
* Quick patch to fix 'rake clean'
SIMP-2714 #comment Fix rake helpers for gpg move
SIMP-2750 #close
> (SIMP-2750) Update to handle moving of the GPGKEYS

- CHANGELOG.md
- lib/simp/rake.rb
- lib/simp/rake/helpers/version.rb
> (SIMP-2482) Restored ability to build from existing tarball

- CHANGELOG.md
- lib/simp/rake/build/code.rb
- lib/simp/rake/helpers/version.rb
> (SIMP-3323) Fix rake code:count

- .travis.yml
- CHANGELOG.md
- Gemfile
- lib/simp/rake/helpers/version.rb
- lib/simp/rake/pupmod/helpers.rb
Added a task to generate a reasonable Git annotation from an RPM-style
CHANGELOG.
Also updated the travis.yml to deploy on tag.
SIMP-3384 #close
> (SIMP-3384) Add changelog -> annotation task

- CHANGELOG.md
- README.md
- lib/simp/rake/helpers/version.rb
- simp-rake-helpers.gemspec
* Updated README for FIPS users
SIMP-3488 #comment Added docs regarding FIPS for users
> (SIMP-3488) Revert Bundler Pinning

- .travis.yml
Add' release on github' deploy step, when the repo is tagged
> (SIMP-3291) simp-rake-helpers: Configure Travis to release

- CHANGELOG.md
- lib/simp/rake/build/pkg.rb
- lib/simp/rake/helpers/version.rb
This is the way that the code was always supposed to have worked.
SIMP-3851 #comment Half of the highline fix for simp_cli
> (SIMP-3851) Try native bundle before clean bundle

- CHANGELOG.md
- lib/simp/rake/helpers/version.rb
- lib/simp/rpm.rb
- spec/acceptance/nodesets/default.yml
- spec/acceptance/pkg_rpm_spec.rb
Fix broken acceptance tests
- Remove logic to build SIMP 4 and SIMP 5 RPMs.
- Remove mock logic
SIMP-3841 #close
> (SIMP-3841) Fix broken simp-rake-helpers acceptance test

- CHANGELOG.md
- lib/simp/rake/build/rpmdeps.rb
- lib/simp/rake/helpers/version.rb
- spec/lib/simp/rake/build/rpmdeps_spec.rb
SIMP-4317 #comment fix RPM release processing
> (SIMP-4317) Fix RPM release processing

- CHANGELOG.md
- lib/simp/rake/build/pkg.rb
- lib/simp/rake/helpers/assets/rpm_spec/simp6.spec
- lib/simp/rake/helpers/assets/rpm_spec/simpdefault.spec
- lib/simp/rake/pkg.rb
- spec/acceptance/10_pkg_rpm_spec.rb
- spec/acceptance/files/testpackage/build/rpm_metadata/requires
- spec/acceptance/files/testpackage/metadata.json
* Ensure that symlinks are removed from modules prior to delivery.
* Make simp6.spec match simpdefault.spec
> (SIMP-5293) Remove symlinks from modules

- CHANGELOG.md
- lib/simp/rake/build/build.rb
- lib/simp/rake/helpers/version.rb
- lib/simp/yum.rb
Minor logic issues but possibly the source of a lot of our download
problems
> (SIMP-5770) Fix download issues

- .travis.yml
- CHANGELOG.md
- lib/simp/rake/helpers/version.rb
- lib/simp/rake/pkg.rb
- lib/simp/rake/pupmod/helpers.rb
- lib/simp/relchecks.rb
- spec/acceptance/nodesets/default.yml
- spec/lib/simp/relchecks_compare_latest_tag_spec.rb
Add the rakelib directory to the list of files/directories to
exclude when comparing with the latest tag in pkg:compare_latest_tag
and compare_latest_tag.
> (SIMP-MAINT) Exclude rakelib for pkg:compare_latest_tag

- CHANGELOG.md
- Gemfile
- lib/simp/rake/helpers/version.rb
- simp-rake-helpers.gemspec
Get versions straightened out so we can release
> (SIMP-MAINT) Fix erroneous version bump

- .travis.yml
This path should start auto-pushing releases to rubygems.org again.
SIMP-6161 #close
> (SIMP-6161) Fixed `tag = true` to `tag IS present`

- CHANGELOG.md
- lib/simp/rake/helpers/version.rb
- simp-rake-helpers.gemspec
- Updated the upperbound for r10k  dependency.
SIMP-6212 #comment rake helpers update
> (SIMP-6212) Update simp-vendored r10k version

- .travis.yml
- CHANGELOG.md
- lib/simp/rake/helpers/version.rb
- simp-rake-helpers.gemspec
> (SIMP-6645) Increase the bundler upper bound to <3

- CHANGELOG.md
- lib/simp/rake/build/rpmdeps.rb
- lib/simp/rake/helpers/version.rb
- spec/lib/simp/rake/build/rpmdeps_spec.rb
* Version information should not be required on dependencies in metadata.json
SIMP-7707 #close
> [SIMP-7707] Fix error on mission dep versions

- CHANGELOG.md
- lib/simp/rake/build/tar.rb
- lib/simp/rake/helpers/version.rb
> [SIMP-7801] Fix automatic deps in 6.4+

- lib/simp/rake/build/pkg.rb
This patch fixes a bug in `Simp::Rake::Build::Pkg`, where
Gem::Version.new could be used to compare packages with and without
RPM-style release suffixes.
Gem::Version interprets an RPM-style release suffix ("relver") like
`1.2.3-4` as `1.2.3.pre.4`, which in SemVer compares as *less* than
`1.2.3`.
This patch works around the issue by using Gem::Version to compare the
X.Y.Z numbers as SemVer, and then comparing relver numbers if the
SemVer numbers are equal.
[SIMP-8836] #close
[SIMP-8836]: https://simp-project.atlassian.net/browse/SIMP-8836
> (SIMP-8836) Fix SemVer comparisons, add details

- CHANGELOG.md
- Gemfile
- lib/simp/local_gpg_signing_key.rb
- spec/acceptance/nodesets/default.yml
[SIMP-9277] #close
[SIMP-9277]: https://simp-project.atlassian.net/browse/SIMP-9277
> (SIMP-9277) Fix GPG handling for GPG 2.1+

- Gemfile
- lib/simp/local_gpg_signing_key.rb
- lib/simp/rake.rb
- lib/simp/rake/helpers/version.rb
- spec/acceptance/nodesets/default.yml
- spec/spec_helper_acceptance.rb
* Bumped the version number
* Checked for GPG commands and provided a notice on failure
* Fixed the nodesets
> (SIMP-9277) Misc minor fixes

- CHANGELOG.md
- lib/simp/rake/build/iso.rb
- lib/simp/rake/helpers/version.rb
- Use the new SimpRepos directory layout when building an ISO using externally
copied repos.
> (SIMP-8606) New ISO repo layout

- .github/workflows/pr_ghaction.yml
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- lib/simp/rake/helpers/assets/rpm_spec/simp6.spec
- lib/simp/rake/helpers/assets/rpm_spec/simpdefault.spec
- spec/acceptance/suites/default/00_pkg_rpm_custom_scriptlets_spec.rb
- spec/acceptance/suites/default/10_pkg_rpm_spec.rb
- spec/acceptance/suites/default/55_build_pkg_signing_spec.rb
Add the DIST qualifier to all build RPMs
SIMP-9885 #close
> (SIMP-9885) Add dist qualifier to all RPMs

- CHANGELOG.md
- lib/simp/rake/build/iso.rb
- lib/simp/rake/helpers/version.rb
> Output full mkisofs command during ISO build

- CHANGELOG.md
- lib/simp/rake/build/auto.rb
- lib/simp/rake/build/deps.rb
- lib/simp/rake/build/iso.rb
- lib/simp/rake/helpers/version.rb
- spec/lib/simp/rake/build/helpers_spec.rb
- Fixed:
- Aligned wtih an API change in the `dirty?` method in `r10k`
Closes #181
> Align with r10k API change

- CHANGELOG.md
- lib/simp/rake/build/iso.rb
- lib/simp/rake/helpers/version.rb
> SIMP_BUILD_reposync_only now properly unpacks the tarball

- CHANGELOG.md
- lib/simp/rake/helpers/assets/rpm_spec/simp6.spec
- lib/simp/rake/helpers/assets/rpm_spec/simpdefault.spec
- lib/simp/rake/helpers/version.rb
* Change the default RPM permissions to 644/755
Closes #188
> Update RPM default permissions

- .github/workflows/add_new_issue_to_triage_project.yml
- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_cleanup.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/tag_deploy_rubygem.yml
and may also apply other updates to ensure conformity.
> Add GHA action to add new issues to triage project

- CHANGELOG.md
- simp-rake-helpers.gemspec
Fixes pupmod bundle install errors
> bumped required puppet version to < 9.0

- CHANGELOG.md
- Gemfile
- lib/simp/ci/gitlab.rb
- lib/simp/componentinfo.rb
- lib/simp/rake/build/auto.rb
- lib/simp/rake/build/build.rb
- lib/simp/rake/build/pkg.rb
- lib/simp/rake/helpers/version.rb
- lib/simp/rake/pupmod/helpers.rb
- rakelib/gitlab_ci.rake
- simp-rake-helpers.gemspec
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/default_ruby3_1.yml
> Support for Ruby 3 and Puppet 8

- .github/workflows/pr_tests.yml
- Gemfile
- lib/simp/rake/helpers/version.rb
- simp-rake-helpers.gemspec
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/default_ruby3_1.yml
> (#221) Updated simp-beaker-helpers dependency
