simp/rubygem-simp-rake-helpers

lib/simp/rake.rb

Just adding a description of the SIMP_GIT_BRANCH environment variable to
the Help message since the 'help' task overrides don't appear to be
working properly.
SIMP-63 #close

(SIMP-63) Add SIMP_GIT_BRANCH to the Help message

---

CHANGELOG.md
lib/simp/rpm.rb

The new format that we're using for GPG signing broke compatibility with
the support Gem.
This adds the appropriate patches.
SIMP-47 #comment Gem update to handle GPG issues

(SIMP-47) Fixed issues with GPG signing

---

CHANGELOG.md
lib/simp/rake/helpers.rb

This patch updates the gem version before publishing to rubygems.org.
SIMP-47  #comment updated rubygem-simp-rake-helpers to 1.0.6
SIMP-196 #close

(SIMP-196) Supplementary cleanup

---

CHANGELOG.md
lib/simp/rake/helpers.rb
lib/simp/rake/pkg.rb
lib/simp/rpm.rb

This spiraled a bit out of control as I was debugging:
1) Sanely ignore any variables in Release tags in RPMs
* This does mean that we probably need to start naming our RPMs by
Version only.
2) Realized that any optimizations we were attempting to do were getting
swallowed up by directory attributes. Now ignore directories and life
is much better.
3) Base all rebuilds on dist/*rpm globs. This may rebuild *all* SRPMs in
the dist directory but this is *probably* what you want anyway.
4) Cleaned up the code a bit.
SIMP_226 #close #comment Well, that escalated quickly....

(SIMP-226) Update to handle 'dist' Releases

---

CHANGELOG.md
lib/simp/rake/helpers.rb
lib/simp/rpm.rb

This adds an exception in the case that the GPG signing command
outright fails.
SIMP-248 #comment Raise error if GPG signing fails. Non-critical.

(SIMP-248) Raise an error if GPG signing fails

---

CHANGELOG.md
lib/simp/rake/helpers.rb
lib/simp/rpm.rb

The RPM signing code needs to only use GPGv1. This patch ensures that it
will nail itself to GPGv1 instead of using the default of GPGv2.
SIMP-237 #comment Fix GPG signing code

(SIMP-FOSS) Update the RPM signing code

---

.rspec
Gemfile
README.md
lib/simp/rake/helpers.rb
simp-rake-helpers.gemspec

Before this patch, requiring the gem 'simp-rake-helpers' would fail if
PUPPET_VERSION was 4 or above.
This patch relaxes the PUPPET_VERSION requirement in the gemspec for
simp-rake-helpers and removed the superfluous 'require' statement in
lib/simp/rake/helpers.rb that had been breaking Travis CI tests using
ruby 1.9.3 with a NoMethodError since SIMP-226.
This patch also increments the gem's version to 1.0.10.
SIMP-208 #close #comment Gemfile honors PUPPET_VERSION, release 1.0.10
SIMP-258 #close #comment removed require in helpers.rb to fix bundler

(SIMP-208) Allow Puppet 4.X in simp-rake-helpers

---

.gitignore
.travis.yml
Rakefile
lib/simp/rake/helpers.rb
lib/simp/rake/pkg.rb
simp-rake-helpers.gemspec
spec/acceptance/files/testpackage/Rakefile
spec/acceptance/files/testpackage/build/testpackage.spec
spec/acceptance/mock_tests_spec.rb
spec/acceptance/nodesets/default.yml
spec/spec_helper_acceptance.rb

Before this commit, a full simp-core ISO build would typically leave
~60GB of redundant chroots under /var/lib/mock.  This limited the
environments where a SIMP ISO could be built.
This patch fixes that problem by adding a post-build action to `rake
pkg:rpm` that runs `mock --clean` to remove the mock chroot unless the
environment variable `SIMP_RAKE_MOCK_cleanup=yes`
SIMP-796 #comment `pkg:rpm` honors `SIMP_RAKE_MOCK_cleanup=yes`
SIMP-796 #comment Configured beaker to test rake-helpers using docker
SIMP-796 #comment Configured docker nodeset to install and run mock
SIMP-796 #comment Added beaker acceptance tests
SIMP-796 #comment Bumped `simp-rake-helpers` gem to 1.0.14
SIMP-232 #comment `pkg:rpm` cleans mock by default
SIMP-796 #close #comment `pkg:rpm` cleans mock by default

(SIMP-796) `pkg:rpm` cleans mock chroot by default

---

Gemfile
README.md
Rakefile
lib/simp/rake/fixtures.rb
lib/simp/rake/helpers.rb
lib/simp/rake/helpers/version.rb
lib/simp/rake/rubygem.rb
simp-rake-helpers.gemspec

SIMP-858 #comment added `helpers/version.rb` to prevent path errors
SIMP-858 #comment `lib/simp/rake/helpers.rb` safe for direct require
SIMP-858 #comment modernized test task definitions in `Rakefile`
SIMP-858 #comment added fixtures tasks
SIMP-858 #close #comment bumped gem to version 1.0.15

(SIMP-858) Roll up extant rake-helpers changes

---

lib/simp/rake/build/auto.rb
lib/simp/rake/build/tar.rb
lib/simp/rake/helpers/version.rb

This patch fixes a post-re-home error by implementing a horribad global
variable (`$simp_tarballs`) in order to pass a data structure back from
`tar:build` and `build:auto`.  In reality, this should be broken into a
shared method (possibly a mixin like `init_member_vars`).  However,
expediency requires this hacky workaround before our next release.
SIMP-192 #comment Made `$simp_tarballs` a global variable. :'(
SIMP-912 #comment bumped gem version to 1.1.2

(SIMP-912) Fix more bugs in ISO build tasks

---

lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb

This patch fixes additional edge case errors within the `iso:build`
portion of `simp:auto` with certain combinations of `SIMP_BUILD_*`
environment variables and relative `iso_paths` strings.
SIMP-192 #comment Fixed nil directory and frozen String errors
SIMP-912 #comment bumped gem version to 1.1.3

(SIMP-912) Fix yet more bugs in ISO build tasks

---

README.md
lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb
simp-rake-helpers.gemspec
spec/lib/simp/rake/pupmod/helpers_spec.rb

This patch re-homes the the Rake tasks common to all `pupmod-simp-*`
repos into the `simp-rake-helpers` gem.
SIMP-932 #comment bumped gem version to `1.2.0` (y-bump)
SIMP-932 #close #comment re-homed pupmod Rakefile tasks to rake-helpers

(SIMP-932) Re-home pupmod Rakefile tasks in gem

---

README.md
lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb
simp-rake-helpers.gemspec

Before this commit, `rake spec` ran spec tests sequentially.
Consequently, large test suites took a very long time to complete.
This patch includes the new rake task `spec_parallel`, which runs spec
tests in parallel.  This has cut some spec test suites' running time
from ~45 min to 1.5 minutes. :rocket:
SIMP-934 #close #comment Added pupmod task `spec_parallel`
SIMP-934 #comment _truly_ bumped gem version to 1.2.0

(SIMP-934) Add `spec_parallel` pupmod task

---

README.md
lib/simp/rake/build/deps.rb
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

Needed a way to easily get all of the changelogs since the last
release.
SIMP-874 #comment Added rake task helper
Change-Id: Ie80cddf2e79684dbbb6b49e54051b15ba88f1df3

(SIMP-874) Add a deps:changelog task for logs

---

CHANGELOG.md
lib/simp/rake/build/deps.rb
lib/simp/rake/helpers/version.rb

The deps:checkout task did not validate that the module was known prior
to attempting to process the module.
This works for clean checkouts but fails if you start adding new repos
to your system.
SIMP-973 #close

(SIMP-973) Fixed deps:checkout failure on unknown

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

Lock gems which depend on ruby 2.2+.
NOTE: This list is subject to change before merge as gems
regularly update and drop ruby < 2.2 support.
SIMP-1033 #close

(SIMP-1033) Remove gem dependencies on ruby 2.2

---

.travis.yml
CHANGELOG.md
README.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

Before this patch, `simp-rake-helpers` mistakenly specified some runtime
dependencies as development dependencies, which prevented the gem from
providing prerequisites to some of the rake tasks it provides.
This update correctly declares the missing runtime dependencies and
bumps the `simp-rake-helpers` gem version to `2.2.2`
SIMP-1040 #comment fixed mislabeled runtime deps
SIMP-1041 #comment updated `simp-rake-helpers` Travis to test 2.0+2.1
SIMP-1040 #comment bumped `simp-rake-helpers` gem to `2.2.2`
Change-Id: I93f9bd0ba154269c6cb8017d8f2a5f6dc1744700

(SIMP-1040) Fixed mislabeled runtime deps

---

lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb

Before this patch, the `box_distro_release` field in the Packer `.json`
file generated by the `build:auto` task contained the absolute path to
the original ISO file.  This patch corrects the oversight to
`box_distro_release`.
SIMP-1042 #comment Bumped `simp-rake-helpers` to `2.1.3`
SIMP-1042 #close #comment  Fixed malformed Packer `box_distro_release`
Change-Id: If4e928a691adbb1459a5445863b3512fb0b3801a

(SIMP-1042) Fixed malformed `box_distro_release`

---

lib/simp/rake/build/build.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

If run without calling bunlder, the code fails with the error
"NameError: uninitialized constant Simp::Rake::Build::Build::Bundler".
Also, updated rake to accept anything between 10 and 12.
SIMP-1108 #close

(SIMP-1108) Update to run without explicit bundler

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

Because Guard requires it at runtime.
SIMP-1178 #close

(SIMP-1178) Pin 'listen' at runtime

---

CHANGELOG.md
lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb

'RedHat' needed to be translated into 'RHEL' to match the files in the
filesystem.
SIMP-1183 #close

(SIMP-1183) Fix issue with RHEL builds

---

CHANGELOG.md
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb

The Rake task for repoclosure was not reliably failing.
This changes the 'sh' call to a %x with a capture and analysis of the
output.
SIMP-964 #close

(SIMP-964) Fail on repoclosure

---

CHANGELOG.md
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/rpm_spec.rb
lib/simp/rake/helpers/version.rb
lib/simp/rake/pkg.rb

This patch adds a Lua-based RPM template to the stack and injects it
into the build process.
By doing this, we can now build *any* Puppet module as an RPM without
forking it.
There must be a well formed metadat.json for this to function properly.
Most importantly, the 'name' field must be '<author>-<module_name>' and
the version number must be intact.
SIMP-1181 #close

(SIMP-1181) Build any module as an RPM

---

CHANGELOG.md
lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb

The issues that were present that caused us to run the recursive bundle
during the ISO build have been rectified.
SIMP-1302 #close
Change-Id: Ibeeec3fdf61bf2365be5e6dadaa6f752d7558d9f

(SIMP-1302) Disable recursive bundle by default

---

CHANGELOG.md
lib/simp/rake/build/deps.rb
lib/simp/rake/helpers/version.rb
spec/lib/simp/rpm_spec.rb

Before this patch, when `rake deps:checkout` was run on a fresh (empty)
checkout of simp-core, it would spam the terminal with spurious warning
messages:
```
Warning: 'src/doc' is not a module...skipping
Warning: 'src/rsync' is not a module...skipping
Warning: 'src/rubygems/simp_cli' is not a module...skipping
Warning: 'src/puppet/modules/grafana' is not a module...skipping
Warning: 'src/puppet/modules/elasticsearch' is not a module...skipping
Warning: 'src/puppet/modules/logstash' is not a module...skipping
Warning: 'src/puppet/modules/file_concat' is not a module...skipping
Warning: 'src/puppet/modules/augeasproviders' is not a module...skipping
No repositories have changes.
```
This patch removes the unneeded warnings, resulting in much cleaner
output:
```
No repositories have changes. …
```

(SIMP-1370) Remove silly `deps:checkout` warnings

---

CHANGELOG.md
lib/simp/rake/helpers/rpm_spec.rb
lib/simp/rake/helpers/version.rb
lib/simp/rake/pkg.rb

* Fixed the template so that it properly brings in the 'requires' and
'release' files from the RPM metadata directory
* Ensure that the appropriate files are copied into the 'dist'
directory so that they make their way into the SOURCES directory
* This needs to be scrapped and redone more cleanly in the future. Got
too clever with the LUA-fu
SIMP-1410 #comment Fixed the RPM spec template
Change-Id: Id4d6fc6c38abba676914c024c43c0ccc558858c6

(SIMP-1410) Updated the RPM spec template

---

CHANGELOG.md
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb

Previously the `pkg:rpmsign` task would fail with hundreds of lines of
mostly unhelpful output if the `rpmsign` package was unavailable.  This
adds a sanity check on the executable, raising an exception if it is not
available, and outputing a more helpful message.
SIMP-1395 #close

(SIMP-1395) Sanity check pkg:rpmsign

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

External packages now require a later version of puppet-lint so we've
pinned to >= 1.0 and < 3.0 to remain compatible after testing.
SIMP-1426 #close
Change-Id: I00108acf276f5d05a55a59d09985c3a88f93a3e8

(SIMP-1426) Update dependency on puppet-lint

---

CHANGELOG.md
lib/simp/rake.rb
lib/simp/rake/build/auto.rb
lib/simp/rake/build/build.rb
lib/simp/rake/build/deps.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb

This update fixes the case where a system is connected to RHN and cannot
use 'curl' to download packages directly.
SIMP-1483 #close

(SIMP-1483) Fix for RHN connected systems

---

lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb

By default, the Blacksmith task `module:tag` with tag module releases
using the convention:
`vX.Y.Z`
This commit configures Blacksmith to use the SIMP tagging convention:
`X.Y.Z`
SIMP-1572 #comment `rake module:tag` tags w/`X.Y.Z` instead of `vX.Y.Z`
SIMP-1572 #comment bumped gem release to 2.5.7
SIMP-1572 #close

(SIMP-1572) Tag modules with `X.Y.Z` format

---

CHANGELOG.md
lib/simp/rake/build/constants.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/rpm_spec.rb
lib/simp/rake/helpers/version.rb

Fixed issues with the code that prevented successful builds with 4.X
and 5.X.
This version should work with all released versions of SIMP
SIMP-1843 #close
Change-Id: I879ca0109682d699674a1e67456a903656efc660

(SIMP-1843) Backwards compatibility fixes

---

CHANGELOG.md
lib/simp/rake/build/auto.rb
lib/simp/rake/build/build.rb
lib/simp/rake/build/clean.rb
lib/simp/rake/build/code.rb
lib/simp/rake/build/constants.rb
lib/simp/rake/build/deps.rb
lib/simp/rake/build/helpers.rb
lib/simp/rake/build/iso.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/build/spec.rb
lib/simp/rake/build/tar.rb
lib/simp/rake/build/unpack.rb
lib/simp/rake/build/upload.rb
lib/simp/rake/helpers/version.rb
lib/simp/rake/pkg.rb
lib/simp/rpm.rb
simp-rake-helpers.gemspec

* Added support for the split SIMP 6 distribution directories
* Fixed issues with required rebuild detection
* Should be backwards compatible with the old repos

(SIMP-222) Add SIMP 6 distribution dir support

---

CHANGELOG.md
lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb

The tarball name in the legacy build section was incompatible with the
new changes.
SIMP-2148 #close

(SIMP-2148) Fix for legacy builds

---

CHANGELOG.md
lib/simp/rake/build/constants.rb
lib/simp/rake/build/iso.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/build/tar.rb
lib/simp/rake/helpers/version.rb

The DVD directory was not adjusted to be in the distribution
directories which caused non-EL7 builds to fail.
SIMP-2253 #close

(SIMP-2253) Look for DVD dir in distro dirs

---

.travis.yml
CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

This commit provides more modern Puppet rake tasks.
SIMP-2572 #comment Updated to `simp-rake-helpers` ~> 1.0
SIMP-2572 #comment Updated to `rake` < 13.0
SIMP-2572 #close

(SIMP-2572) Update outdated dependencies

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
lib/simp/rake/pkg.rb

Added a 'pkg:check_version' rake task to validate that the repository,
at the current HEAD, does not require an update to the metadata.json or
CHANGELOG.
The output will need to be manually reviewed because the likelihood of
false positives for non-SIMP repos is quite high and there is no
foolproof way to know if a repo is a SIMP maintained repo.
SIMP-2860 #close

(SIMP-2860) Added a 'pkg:check_version' rake task

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

Starting with Beaker 3.13.0 (BKR-1049), releases of Beaker 3.X will now
match the latest supported PE vendored ruby (2.1.9).  This relieves us
of the need to maintain our own form of Beaker 2.x.  The version of
beaker has been pinned (via simp-rake-helpers) since the introduction of
3.X.
This patch updates simp-rake-helpers to use beaker 3.X and bumps the
version of simp-rake-helpers to 3.5.0.
SIMP-3020 #close #comment version bump to 3.5.0

(SIMP-3020) Add support for Beaker 3.x

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb

Created a rake task to identify simp puppet modules for which
a new version is warranted.  This task fails on a variety of
version problems, so it can be used as a lint task in CI.
SIMP-3372 #close

(SIMP-3372) Create rake task for tag compare

---

.travis.yml
CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

This pulls in simp-rspec-puppet-facts 2.0.0 which is a breaking change
since all of the facts were updated.
SIMP-3466 #comment update to support facter 2.5

(SIMP-3466) Update to support facter 2.5

---

CHANGELOG.md
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb
lib/simp/rake/pkg.rb

Determine the build/rpm_metadata/* files when the pkg:rpm
rake task is called, not when the rake object is constructed.
SIMP-3837 #comment simp-rake-helpers fix

(SIMP-3837) simp-rake-helpers:  Fix for simp-doc RPM build

---

CHANGELOG.md
lib/simp/rake/build/deps.rb
lib/simp/rake/helpers/version.rb

This commit fixes a bug in `deps:record` that prevented recording to a
custom Puppetfile._[method]_.  It also adds a new `:reference` parameter
to `deps:record` to specify a new Puppetfile for referencing which repos
to record.
SIMP-3834 #close

(SIMP-3843) Enhance `deps:record` task

---

CHANGELOG.md
lib/simp/rake/build/unpack.rb
lib/simp/rake/helpers/version.rb

Fixed a last vestige of the old 'RHEL' markings in the 'unpack' task.
This is required to build RHEL releases.
SIMP-3421 #comment Fixed RHEL incompatibility in rake-helpers

(SIMP-3421) Changed 'RHEL' to 'RedHat'

---

lib/simp/rake/build/rpmdeps.rb
spec/lib/simp/rake/build/rpmdeps_spec.rb

Discovered that the Obsoletes in the generated spec file was only '>'
not '>=' as it should have been.
It was causing upgrades to break.
SIMP-3748 #comment Fix Obsoletes in RPM spec files

(SIMP-3748) Obsoletes must be '>='

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb
lib/simp/rpm.rb

Switched back to Gem::Version from the inbuilt Puppet version
comparator since Gem::Version matches the semantics for RPM versioning.
SIMP-3954 #comment Switch back to Gem::Version

(SIMP-3954) Switch to Gem::Version for comparisons

---

CHANGELOG.md
lib/simp/rake/build/rpmdeps.rb
lib/simp/rake/helpers/version.rb
spec/lib/simp/rake/build/files/dependencies.yaml
spec/lib/simp/rake/build/rpmdeps_spec.rb

Add ability to specify external, non-module, RPM dependencies for
a checked-out repo from `simp-core/build/rpm/dependencies.yaml`
Required to add TOML gem dependencies to puppet-grafana RPM.
SIMP-4389 #close

(SIMP-4389) Specify external deps for generated RPMs

---

CHANGELOG.md
lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

* Add a conditional check, so if a valid tarball already exists,
and we are configured not to prompt, to just use the tarball
and continue the build.
SIMP-4431 #close

(SIMP-4431) Build SIMP ISO automatically when given an overlay

---

CHANGELOG.md
README.md
lib/simp/rake/build/deps.rb
lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb
spec/lib/simp/rpm_spec.rb

* Add support for setting SIMP_RSPEC_PUPPETFILE and/or
SIMP_RSPEC_MODULEPATH to create a custom fixtures.yml based on a
Puppetfile, the modules in a directory, or the combination of both.
SIMP-4289 #close

(SIMP-4271) Add rspec Puppetfile support

---

CHANGELOG.md
lib/simp/rake/build/constants.rb
lib/simp/rake/helpers/version.rb

A recent commit inadvertently removed the ability for the
`SIMP_BUILD_distro` to specify a specific build target for SIMP by
hard-coding each value to the Facter facts of the build system.
This patch reintroduces support for `SIMP_BUILD_distro` and falls back
to the Facter values if it isn't set.
SIMP-4957 #close

(SIMP-4957) Fix regression in `SIMP_BUILD_distro`

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

The fog-openstack gem dropped support for Ruby 1.9 suddenly and all of
our tests are now failing.
While this is a bit of a band-aid, it should let us continue with
testing until we can move off of 1.9 at the end of the year.

(SIMP-MAINT) Emergency fix for fog-openstack

---

.travis.yml
CHANGELOG.md
lib/simp/rake/pkg.rb
lib/simp/relchecks.rb
spec/acceptance/30_pkg_misc_spec.rb
spec/acceptance/files/asset/Rakefile
spec/acceptance/files/asset/build/asset.spec
spec/acceptance/files/asset_with_misordered_entries/Rakefile
spec/acceptance/files/asset_with_misordered_entries/build/asset_with_misordered_entries.spec
spec/acceptance/files/module/CHANGELOG
spec/acceptance/files/module/Rakefile
spec/acceptance/files/module/metadata.json
spec/acceptance/files/module_with_misordered_entries/CHANGELOG
spec/acceptance/files/module_with_misordered_entries/Rakefile
spec/acceptance/files/module_with_misordered_entries/metadata.json
spec/acceptance/nodesets/default.yml
spec/lib/simp/files/relchecks_check_rpm_changelog_spec/asset/build/asset.spec
spec/lib/simp/files/relchecks_check_rpm_changelog_spec/asset_with_misordered_entries/build/asset_with_misordered_entries.spec
spec/lib/simp/files/relchecks_check_rpm_changelog_spec/module/CHANGELOG
spec/lib/simp/files/relchecks_check_rpm_changelog_spec/module/metadata.json
spec/lib/simp/files/relchecks_check_rpm_changelog_spec/module_with_misordered_entries/CHANGELOG
spec/lib/simp/files/relchecks_check_rpm_changelog_spec/module_with_misordered_entries/metadata.json
spec/lib/simp/relchecks_check_rpm_changelog_spec.rb

* Update pkg:create_tag_change to verify all CHANGELOG entries for a component
are in reverse chronological order, not just the entries for the latest
version.
* Add pkg:check_rpm_changelog task to verify the 'rpm' command can parse a
component's changelog.
SIMP-5011 #close

(SIMP-5011) Check for rpm changelog errors

---

CHANGELOG.md
lib/simp/rake/build/constants.rb
lib/simp/rake/helpers/version.rb
lib/simp/rpm.rb
spec/acceptance/10_pkg_rpm_spec.rb
spec/acceptance/nodesets/default.yml
spec/lib/simp/rpm_spec.rb

Since b790439 (#91), it has not been possible to build SIMP RPMs
and ISOs for any OS other than the OS of the build host.
This patch restores the ability to build SIMP ISOs for other OSes by
introducing the environment variable `SIMP_RPM_dist` and updating the
logic in `Simp::Rake::Build::Constants`
SIMP-4969 #close

(SIMP-4969) Add `SIMP_RPM_dist` to `SIMP::RPM`

---

CHANGELOG.md
lib/simp/rake/build/iso.rb
lib/simp/rake/helpers/version.rb

There were several options missing from the mkisofs command that fixed
UEFI booting for some hardware.
SIMP-5202 #close

(SIMP-5202) Add UEFI options to mkisofs command

---

CHANGELOG.md
lib/simp/rake/helpers/assets/rpm_spec/simpdefault.spec
spec/acceptance/00_pkg_rpm_custom_scriptlets_spec.rb
spec/acceptance/10_pkg_rpm_spec.rb

LUA for puppet modules now only executes
/usr/local/sbin/simp_rake_helper in its scriptlets,
if that file exists.
SIMP-2780 #comment simp-rake-helpers LUA update

(SIMP-2780) Handle edge case in module spec files

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
lib/simp/yum.rb

Do not try to only use the system cache for yum operations since this
silently causes all EL6 builds to be rebuilt instead of having the
remote RPM downloaded if necessary. The original code can't really work
anyway since there isn't a local cache unitl after yum runs.
After yum runs, the local cache will be preferred unless it has expired
anyway.

(SIMP-5349) Fix long standing EL 6 bug

---

CHANGELOG.md
lib/simp/packer/iso_vars_json.rb
lib/simp/rake/build/auto.rb
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec
spec/lib/simp/packer/iso_vars_json_spec.rb

simp-packer needs more reliable information about the distribution OS
from the vars.json file (generated by `rake build:auto` along with every
SIMP ISO).
This patch adds the following distribution OS keys:
* `dist_os_flavor`
* `dist_os_version`
* `dist_os_maj_version`
* `dist_source_isos`
And the following version/ build metadata keys:
* `simp_vars_version`
* `packer_src_type`
* `iso_builder`
* `iso_builder_version`
* `git_commit`
SIMP-3804 #comment Added `dist_source_isos`, `dist_os_flavor`
SIMP-3804 #close #comment Added `dist_os_version`, `dist_os_maj_version`
SIMP-5506 #close

(SIMP-5506) Generate vars.json with dist OS data

---

CHANGELOG.md
lib/simp/rake/build/tar.rb
lib/simp/rake/helpers/version.rb

- updated the list of packages to check for when validating the
tar overlay to match new name, simp-rsync-environment,
simp-environment-skeleton,  and additional rpm, simp-environment-selinux-policy.
SIMP-6402 #comment

(SIMP-6402) Rsync and Environment name change

---

CHANGELOG.md
lib/simp/rake/helpers/assets/rpm_spec/simp6.spec
lib/simp/rake/helpers/assets/rpm_spec/simpdefault.spec
lib/simp/rake/helpers/version.rb
spec/acceptance/00_pkg_rpm_custom_scriptlets_spec.rb
spec/acceptance/10_pkg_rpm_spec.rb
spec/acceptance/20_pkg_rpm_upgrade_spec.rb
spec/acceptance/nodesets/default.yml

Fixed 2 bugs in the SIMP Puppet module generated RPM spec files
* When SIMP Puppet module RPMs were installed, they created the wrong
state directory, '/%{_localstatedir}/lib/rpm-state/simp-adapter'.
This incorrect directory was created because the '_localstatedir'
RPM macro was not evaluated at run time.
* The %preun and $postun scriptlet comments were incorrect.
SIMP-6933 #close
SIMP-6092 #close

(SIMP-6933) SIMP module RPMs use wrong state dir

---

CHANGELOG.md
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb

There is no reason to fail during the processing of pkg:check_published
since we always want as much data as possible.
This now emits useful error messages

(SIMP-MAINT) Don't fail in pkg:check_published

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
simp-rake-helpers.gemspec

* Allow v3 of simp-rspec-puppet-facts
* Fix '~> 0' notation

(SIMP-MAINT) simp-rspec-puppet-facts version bump

---

CHANGELOG.md
lib/simp/rake/build/rpmdeps.rb
lib/simp/rake/helpers/version.rb
spec/lib/simp/rake/build/files/changed_name_mod/metadata.json
spec/lib/simp/rake/build/files/unmanaged_mod/metadata.json
spec/lib/simp/rake/build/rpmdeps_spec.rb

SIMP optional dependencies in a module's metadata json are
now included in the RPM requires list.  This change ensures
that upon RPM install, the optional dependencies are available
in the SIMP-managed local Git repos.
SIMP-7594 #close

(SIMP-7594) Include SIMP optional deps in RPM requires

---

lib/simp/componentinfo.rb
lib/simp/rake/helpers/assets/rpm_spec/simp6.spec
lib/simp/rake/helpers/assets/rpm_spec/simpdefault.spec
spec/lib/simp/componentinfo_spec.rb
spec/lib/simp/files/componentinfo_spec/module_with_prerelease_dash_in_version/CHANGELOG
spec/lib/simp/files/componentinfo_spec/module_with_prerelease_dash_in_version/metadata.json
spec/lib/simp/files/testpackage-rc0.spec
spec/lib/simp/rpm_spec.rb

Before this patch,a Puppet module version like `1.2.3-rc0` would break
RPM-related operations in simp-rake-helpers: The .spec files used the
metadata.json's `version` field in its entirety, but the string `-rc0`
is not valid for an RPM's `Version` field.
An RPM .spec file `Version` field is required to be in `\d+\.\d+\.\d+`
format.
Some Puppet orgs (voxpupuli) append `-rc0` to the version in their
modules' metadata.json.   This denotes prerelease status during
development and acts as a built-in releng safety check (because the
Puppet Forge only accepts release in SemVer \d+\.\d+\.\d+ release
format).
Example:
https://github.com/simp/puppet-gitlab/blob/5fb9bb8ec3eee7af31c1c82a53eef56201788eeb/metadata.json#L3
This patch corrects the issue by splitting a Puppet module's `version`
string at …

(SIMP-7600) Chop version at '-' in RPM .spec files

---

CHANGELOG.md
lib/simp/rake/helpers/version.rb
lib/simp/relchecks.rb
spec/lib/simp/relchecks_compare_latest_tag_spec.rb

The patch modifies the `rake pkg:compare_latest_tag` to consider `*.md`
files (like `REFERENCE.md`) as non mission-impacting updates.  This
will enable CI pipelines to run the rest of their steps.
[SIMP-8134] #close
[SIMP-8134]: https://simp-project.atlassian.net/browse/SIMP-8134

(SIMP-8134) Allow *.md in `pkg:compare_latest_tag`

---

lib/simp/rake/build/pkg.rb

Before this patch, running `rake clean` and `rake clobber` in the
simp-core project would fail with errors if any modules from
Puppetfile.<method> are missing from the src/puppet/modules/ directory.
This patch fixes the issue by skipping any missing directories inside
the Parallel blocks.
SIMP-8335 #close

(SIMP-8335) Fix `rake clean` with missing modules

---

spec/lib/simp/rake/pupmod/fixtures/othermod/Gemfile

Dependabot was flagging CVEs in gem dependencies inside the minimal
'not-simp' test module fixture (last updated in 2017).  This patch
removes the Ruby 1.8.7 constraints and should do a better job at
remaining current over time.
Note: the env var `PUPPET_VERSION` is explicitly set by all SIMP CI
pipelines, so it will change depending on the matrix iteration.

(SIMP-MAINT) Update deps in spec fixture Gemfile

---

CHANGELOG.md
lib/simp/rake/build/build.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb

Fixed:
* Use `with_unbundled_env` when supported and `with_clean_env`
otherwise
[SIMP-8353] #close
[SIMP-8353]: https://simp-project.atlassian.net/browse/SIMP-8353

(SIMP-8353) Support with_unbundled_env

---

lib/simp/rake/build/build.rb
lib/simp/rake/build/constants.rb

This commit untangles the `build:yum:*` tasks from `yum:prep`'s
redundant requirement on the undocumented ENV var `SIMP_BUILD_yum_dir`.
`build:yum:scaffold` now determines the target dir based on its own
arguments, which propogates to the rest of the `build:yum:*` tasks
(because they all require :scaffold).
This patch also enhances `build:yum:scaffold` to create an example
`packages.yaml` file when the target directory's `packages.yaml` does
not exist.
[SIMP-8594] #close
[SIMP-8594]: https://simp-project.atlassian.net/browse/SIMP-8594

(SIMP-8594) Untangle build:yum:* from hidden ENV

---

.gitlab-ci.yml
.travis.yml
spec/lib/simp/ci/gitlab_spec.rb
spec/lib/simp/componentinfo_spec.rb
spec/lib/simp/rake/build/helpers_spec.rb
spec/lib/simp/rake/build/rpmdeps_spec.rb
spec/lib/simp/rake_spec.rb
spec/lib/simp/relchecks_compare_latest_tag_spec.rb
spec/lib/simp/rpm_spec.rb
spec/spec_helper.rb

This patch:
* Removes ALL TESTS from the Travis CI pipeline
* Modernizes and DRYs up the GitLab CI pipeline
* Fixes the "missing rpmbuild" problem with docker-based spec tests and
removes the "allow_failures" workaround.
* Mocks tests that rely on local OS/facts to work (and fail in GitLab CI)
* Converts mocha stubs to rspec-mocks expectations
[SIMP-8803] #close
[SIMP-8337] #close #comment Converted to mock failing GitLab CI tests
[SIMP-8803]: https://simp-project.atlassian.net/browse/SIMP-8803
[SIMP-8337]: https://simp-project.atlassian.net/browse/SIMP-8337

(SIMP-8803) Remove Travis CI tests

---

CHANGELOG.md
Gemfile
lib/simp/componentinfo.rb
lib/simp/rpm.rb
simp-rake-helpers.gemspec
spec/lib/simp/relchecks_check_rpm_changelog_spec.rb

Added:
* Support for Puppet 7
Fixed
* Work around issues with querying RPM spec file changelogs using RPM version 5.15.0+
[SIMP-8822] #close
[SIMP-8822]: https://simp-project.atlassian.net/browse/SIMP-8822

(SIMP-8822) Add suport for Puppet 7

---

.github/workflows.local.json

This patch customizes the tasks and locations for the GHA tag-on-release
workflow to use the project's custom build task.
[SIMP-9743] #close #comment Added workflows.local.json
[SIMP-9743]: https://simp-project.atlassian.net/browse/SIMP-9743

(SIMP-9743) Add workflows.local.json

---

.github/workflows/tag_deploy_rubygem.yml

This patch updates the GHA tag-on-release to the standardized rubygem
tag-on-release workflow.
[SIMP-9743] #close #comment Updated GHA release workflow
[SIMP-9743]: https://simp-project.atlassian.net/browse/SIMP-9743

(SIMP-9743) Update GHA release workflow

---

CHANGELOG.md
lib/simp/rake/build/build.rb
lib/simp/rake/build/iso.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/build/spec.rb
lib/simp/rake/build/tar.rb
lib/simp/rake/build/upload.rb
lib/simp/rake/helpers/version.rb

Before this patch, tasks with `@build_dir = $simp6_build_dir` would end
up with `@build_dir` as `nil` if run independently from the `build:auto`
task.  This patch sets `@build_dir` to `@distro_build_dir` if
`$simp6_build_dir` is `nil`.
[SIMP-9746] #close
[SIMP-9746]: https://simp-project.atlassian.net/browse/SIMP-9746

(SIMP-9746) Default @build_dir to @distro_build_dir

---

CHANGELOG.md
lib/simp/rake/build/unpack.rb

Before this patch, running `rake unpack` on a valid ISO file from the
EL8 build container would fail with the error, `Error: The file provided
is not a valid ISO.`  It seems that on EL8, the expected `ISO 9660`
string is no longer guaranteed to returned as the first match.
This patch fixes the issue by running `file --keep-going` to return ALL
matches, which still include the expected `ISO 9660` string.
[SIMP-9748] #close
[SIMP-9748]: https://simp-project.atlassian.net/browse/SIMP-9748

(SIMP-9748) Fix `not a valid ISO` error on EL8

---

.github/workflows/pr_glci.yml
.github/workflows/pr_glci_cleanup.yml
.github/workflows/tag_deploy_rubygem.yml
.gitlab-ci.yml

GitHub actions' Ubuntu 16.04 environment will be removed on Sept 20,
2021.  This patch migrates all workflow using the `ubuntu-16.04`
environment to `ubuntu-latest`.
and may apply other updates to ensure conformity.
[SIMP-10542] #close
[SIMP-10450] #comment Add `release_rpms` to rubygem-simp-rake-helpers
[SIMP-10542]: https://simp-project.atlassian.net/browse/SIMP-10542
[SIMP-10450]: https://simp-project.atlassian.net/browse/SIMP-10450

(SIMP-10450) GHA: Update ubuntu-16.04 to latest

---

.github/workflows/tag_deploy_rubygem.yml

This commit rolls up various improvements to the GHA tag & release
workflows, particularly:
* Tagged releases build a matrix of RPMs: (EL8 *and* EL7)
* Tagged release logic supports pre/post-release tag formats
* New arguments in `release_rpms.yml`: `path_to_build` and `verbose`
* Ensure jobs run on `ubuntu-latest`
* Fixes for variable edge cases and inter-job dependencies
and may apply other updates to ensure conformity.
[SIMP-10645] #close
[SIMP-10633] #comment Add `release_rpms` to rubygem-simp-rake-helpers
[SIMP-10645]: https://simp-project.atlassian.net/browse/SIMP-10645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10633]: …

(SIMP-10633) Update standardized assets

---

.github/workflows/tag_deploy_rubygem.yml

This commit rolls up various improvements to the GHA tag & release
workflows, particularly:
* Un-borking GHA pipeline logic to publish to rubygems.org
and may apply other updates to ensure conformity.
[SIMP-10731] #close
[SIMP-10729] #comment Update rubygem-simp-rake-helpers
[SIMP-10731]: https://simp-project.atlassian.net/browse/SIMP-10731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10729]: https://simp-project.atlassian.net/browse/SIMP-10729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(SIMP-10729) Fix GHA release to rubygems.org

---

CHANGELOG.md
lib/simp/rake/build/iso.rb

* The tarball unpack exclusions were too aggressive. The `SIMP/GPGKEYS`
directory is now preserved properly.
Closes #190

Preserve the SIMP/GPGKEYS directory

---

CHANGELOG.md
lib/simp/rake/build/rpmdeps.rb
lib/simp/rake/helpers/version.rb
spec/lib/simp/rake/build/files/dependencies.yaml
spec/lib/simp/rake/build/rpmdeps_spec.rb

* Users now have the ability to set version limits in the `dependencies.yaml`
file that will override those in the `metadata.json`
Closes #192

Allow Overriding RPM Requires Versions

---

.github/workflows/pr_ghaction.yml
CHANGELOG.md
Gemfile
lib/simp/rake/helpers/version.rb
lib/simp/rake/pupmod/helpers.rb
simp-rake-helpers.gemspec

- Added
- The `puppet-lint-optional_default-check` was added to prevent setting
`Optional` parameters with default values.

Add `puppet-lint-optional_default-check`

---

CHANGELOG.md
lib/simp/rake/build/rpmdeps.rb
lib/simp/rake/helpers/version.rb
spec/lib/simp/rake/build/files/dependencies.yaml
spec/lib/simp/rake/build/rpmdeps_spec.rb

- The RPM dependency file can now use `ignores` to remove items instead of
needing to redefine the entire dependency stack to remove deps
Closes: #195
Refs: simp/simp-core#853

Support `ignores` in RPM dependency overrides

---

CHANGELOG.md
lib/simp/rake/build/iso.rb
lib/simp/rake/helpers/version.rb

Fixed an edge case where the `SIMP` directory YUM metadata was not
present if you used `reposync` for everything but the `SIMP` directory
Closes #197

Fix missing SIMP metadata with mixed `reposync`

---

CHANGELOG.md
lib/simp/rake/build/auto.rb
lib/simp/rake/build/pkg.rb
lib/simp/rake/build/unpack.rb
lib/simp/rake/helpers/version.rb

Added:
- `SIMP_BUILD_reposync_only` now excludes RPMs and yum repos from the ISO
`unpack` task
Fixed:
- Change common repo name `base` to avoid repoclosure conflict warnings
- EL7 ISO unpack no longer interferes with reposync repos when
`SIMP_BUILD_reposync_only=yes`

Ensure `reposync_only` uses ONLY reposync repos

---

CHANGELOG.md
lib/simp/rake/build/pkg.rb
lib/simp/rake/helpers/version.rb

- Added:
- `pkg:single` will skip the `require_rebuild?` logic when `SIMP_BUILD_PKG_require_rebuild=yes`
- Fixed:
- It was impossible to build simp-doc if RPM was published to yum repos; can now use `SIMP_BUILD_PKG_require_rebuild=yes`

Add SIMP_BUILD_PKG_require_rebuild=yes

---

.github/workflows/tag_deploy_rubygem.yml

* Replace deprecated create-release@v1 
* Convert the remaining ::set-output GHA workflows
and may also apply other updates to ensure conformity.

GHA workflow deprecations updates

---

.github/workflows/pr_acceptance.yml
CHANGELOG.md
lib/simp/rake/build/iso.rb
lib/simp/rake/helpers/version.rb

The `iso:build` repoclosure task is presently unskippable, but `repoclosure` itself doesn't work with modular repos. In fact, it probably never can: https://bugzilla.redhat.com/show_bug.cgi?id=1547041
This patch disables the repoclosure step by default, and adds an environment variable, `SIMP_BUILD_repoclosure` to re-enable it when set to `yes`.
Fixes #217

Add SIMP_BUILD_repoclosure var, default=no
